# Generated by Django 4.1.3 on 2022-11-19 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_disponible', models.CharField(max_length=2)),
                ('disp_precio', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.CharField(max_length=45)),
                ('fecha_final', models.CharField(max_length=45)),
                ('precio', models.CharField(max_length=45)),
                ('inmueble_inmu_id', models.ForeignKey(blank=True, db_column='Inmueble_INMU_ID', max_length=45, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.tblmaestra')),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_alquiler',
            },
        ),
        migrations.CreateModel(
            name='TblPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_fecha', models.CharField(db_column='PAGO_fecha', max_length=45)),
                ('pago_valor', models.CharField(db_column='PAGO_valor', max_length=45)),
                ('tbl_alquiler_alqu_id', models.ForeignKey(blank=True, db_column='tbl_alquiler_ALQU_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.tblalquiler')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.tblmaestra')),
            ],
            options={
                'db_table': 'tbl_pago',
            },
        ),
        migrations.CreateModel(
            name='TblInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=45)),
                ('estrato', models.CharField(max_length=45)),
                ('longitud', models.CharField(blank=True, max_length=45, null=True)),
                ('latitud', models.CharField(blank=True, max_length=45, null=True)),
                ('num_pisos', models.IntegerField()),
                ('num_baños', models.IntegerField()),
                ('num_habitaciones', models.IntegerField()),
                ('url_imagenes', models.CharField(max_length=1000)),
                ('superficie', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('dueño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pais_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='personas.tblmaestra')),
                ('tipo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.tblmaestra')),
                ('tipo_inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tinmueble', to='personas.tblmaestra')),
            ],
            options={
                'db_table': 'tbl_Inmueble',
            },
        ),
    ]
