# Generated by Django 4.1.3 on 2022-11-19 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maes_nombre', models.CharField(blank=True, db_column='MAES_NOMBRE', max_length=45, null=True)),
                ('maes_dependencia', models.CharField(blank=True, db_column='MAES_DEPENDENCIA', max_length=45, null=True)),
                ('maes_valor', models.CharField(blank=True, db_column='MAES_VALOR', max_length=45, null=True)),
                ('maes_estado', models.CharField(blank=True, db_column='MAES_ESTADO', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_maestra',
            },
        ),
        migrations.CreateModel(
            name='TblPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('num_identidad', models.CharField(max_length=45)),
                ('tipo_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.tblmaestra')),
                ('tipo_sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexo', to='personas.tblmaestra')),
            ],
            options={
                'db_table': 'tbl_persona',
            },
        ),
        migrations.CreateModel(
            name='TblDueñoHasInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble_inmu_id', models.ForeignKey(blank=True, db_column='Inmueble_INMU_ID', max_length=45, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.tblmaestra')),
                ('tbl_dueño_id', models.ForeignKey(blank=True, db_column='tbl_dueño_ID', max_length=45, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_dueño_has_Inmueble',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clie_nacionalidad', models.CharField(max_length=20)),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.tblmaestra')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.tblpersona')),
            ],
        ),
    ]
